In [ ]:
INSTALLATION OF NUMPY:

In [1]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
type(x)

numpy.ndarray

In [7]:
numbers=[10,20,30,40]
y=np.array(numbers)
y

array([10, 20, 30, 40])

In [8]:
matrices_of_zeros=np.zeros((4,4))
matrices_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
matrices_of_ones=np.ones((5,5))
matrices_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
matrices_of_ones_int=np.ones((4,4),dtype=np.int32)
matrices_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])