In [ ]:
CONTINUATION TO NUMPY:

In [1]:
import numpy as np

In [2]:
store_empty=np.empty((2,3))
store_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
store_eye=np.eye(3) #Identity  matrix implementation

store_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
store_of_evens=np.arange(2,31,2)
store_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
store_of_floats=np.arange(0,2,0.3)
store_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
np.arange(6) ----1d


array([0, 1, 2, 3, 4, 5])

In [22]:
array_nd=np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
array_nd.shape

(3, 2)

In [24]:
store=np.arange(60).reshape(5,6,2)
store

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [25]:
store.shape

(5, 6, 2)

In [26]:
array_2d=np.array([4,2,8],[6,3,1])
array_2d

TypeError: data type not understood